stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw
    outs:
      - data/processed
  train:
    cmd: python src/model_training.py
    deps:
      - data/processed
    outs:
      - models/best_rf_model
      - reports/figures/confusion_matrix.png
      - reports/figures/feature_importance.png

  deploy:
    cmd: python src/api_deployment.py
    deps:
      - models/best_rf_model
  drift:
    cmd: python src/drift_detection.py
    deps:
      - data/processed